# Specify the dataset and its parameters
[data]
test.dataset_name = "tartantest"
#test.data_path = <path to tartan test data>
test.batch_size = 16
test.combined = false
test.modality = "img"

# Provide model type and its params
[model]
save_dir = "models"
#model_path = <path to trained model>
params.full = true
params.frontend = "PWC"
params.cache = true

# Inference time parameters
[posefm]
device = "cuda"
conditioning = "img"
sampling.num_t = 5
