# Specify training hyperparams
[trainer]
lr = 0.0005
epochs = 50
print_every = 1
device = "cuda"
conditioning = "img"

# Specify the dataset and its parameters
[data]
train.dataset_name = "tartantrain"
#train.data_path = <specify path to tartan train data>
train.batch_size = 96
train.val_split = 0.2
train.num_workers = 16
train.modality = "img"

# Provide model params
[model]
save_dir = "models"
# model_path = <path to pretrained model>
freeze = true # Freeze frontend
params.full = true
params.frontend = "PWC"
